/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AdminStats = IDL.Record({
  'soldListings' : IDL.Nat,
  'uniqueSellers' : IDL.Nat,
  'activeListings' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'brandBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'listingId' : IDL.Text,
  'createdAt' : IDL.Int,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'listingTitle' : IDL.Text,
});
export const ConversationSummary = IDL.Record({
  'lastMessageAt' : IDL.Int,
  'listingId' : IDL.Text,
  'lastMessage' : IDL.Text,
  'otherParty' : IDL.Principal,
  'unreadCount' : IDL.Nat,
  'listingTitle' : IDL.Text,
});
export const SellerSummary = IDL.Record({
  'soldListings' : IDL.Nat,
  'activeListings' : IDL.Nat,
  'seller' : IDL.Principal,
  'totalListings' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminDeleteAllListingsBySeller' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteListing' : IDL.Func([IDL.Text], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListingsAdmin' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getConversationSummaries' : IDL.Func(
      [],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getInboxMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
  'getListingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getSellerSummaries' : IDL.Func([], [IDL.Vec(SellerSummary)], ['query']),
  'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'initAdmin' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsSold' : IDL.Func([IDL.Text], [], []),
  'markConversationRead' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'replyMessage' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AdminStats = IDL.Record({
    'soldListings' : IDL.Nat,
    'uniqueSellers' : IDL.Nat,
    'activeListings' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'brandBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'listingId' : IDL.Text,
    'createdAt' : IDL.Int,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'listingTitle' : IDL.Text,
  });
  const ConversationSummary = IDL.Record({
    'lastMessageAt' : IDL.Int,
    'listingId' : IDL.Text,
    'lastMessage' : IDL.Text,
    'otherParty' : IDL.Principal,
    'unreadCount' : IDL.Nat,
    'listingTitle' : IDL.Text,
  });
  const SellerSummary = IDL.Record({
    'soldListings' : IDL.Nat,
    'activeListings' : IDL.Nat,
    'seller' : IDL.Principal,
    'totalListings' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminDeleteAllListingsBySeller' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteListing' : IDL.Func([IDL.Text], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListingsAdmin' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getConversationSummaries' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getInboxMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
    'getListingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getSellerSummaries' : IDL.Func([], [IDL.Vec(SellerSummary)], ['query']),
    'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'initAdmin' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsSold' : IDL.Func([IDL.Text], [], []),
    'markConversationRead' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'replyMessage' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };