/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
  'getListingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'markAsSold' : IDL.Func([IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
    'getListingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'markAsSold' : IDL.Func([IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };