/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'soldListings' : bigint,
  'uniqueSellers' : bigint,
  'activeListings' : bigint,
  'totalListings' : bigint,
  'brandBreakdown' : Array<[string, bigint]>,
}
export interface AnalyticsData {
  'totalMessages' : bigint,
  'dailyMessages' : Array<[string, bigint]>,
  'dailyListings' : Array<[string, bigint]>,
}
export interface ConversationSummary {
  'lastMessageAt' : bigint,
  'listingId' : string,
  'lastMessage' : string,
  'otherParty' : Principal,
  'unreadCount' : bigint,
  'listingTitle' : string,
}
export interface Listing {
  'id' : string,
  'model' : string,
  'title' : string,
  'createdAt' : bigint,
  'sold' : boolean,
  'description' : string,
  'seller' : Principal,
  'imageUrl' : string,
  'brand' : string,
  'price' : bigint,
  'condition' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'listingId' : string,
  'createdAt' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'listingTitle' : string,
}
export interface SellerSummary {
  'soldListings' : bigint,
  'activeListings' : bigint,
  'seller' : Principal,
  'totalListings' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminDeleteAllListingsBySeller' : ActorMethod<[Principal], undefined>,
  'adminDeleteListing' : ActorMethod<[string], undefined>,
  'createListing' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    string
  >,
  'deleteListing' : ActorMethod<[string], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllListingsAdmin' : ActorMethod<[], Array<Listing>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getConversation' : ActorMethod<[string, Principal], Array<Message>>,
  'getConversationSummaries' : ActorMethod<[], Array<ConversationSummary>>,
  'getInboxMessages' : ActorMethod<[], Array<Message>>,
  'getListing' : ActorMethod<[string], Listing>,
  'getListingsByUser' : ActorMethod<[Principal], Array<Listing>>,
  'getSellerSummaries' : ActorMethod<[], Array<SellerSummary>>,
  'getSentMessages' : ActorMethod<[], Array<Message>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'initAdmin' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isPinSet' : ActorMethod<[], boolean>,
  'markAsSold' : ActorMethod<[string], undefined>,
  'markConversationRead' : ActorMethod<[string, Principal], undefined>,
  'replyMessage' : ActorMethod<[string, Principal, string], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'setAdminPin' : ActorMethod<[string], undefined>,
  'updateListing' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    undefined
  >,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];